### ISSUE TITLE
Add airplane mode tile

### ISSUE THREAD

**Issue by CaseyBakey** [CasperVerswijvelt/Better-Internet-Tiles#13]
Hello there,

It's a shame to need an additionnal app to do what we were able to do via ADB on Android 12, but your app does an amazing job at it, and it's FOSS so thank you for that!

In the meantime, I was wondering if you would be able to fix another gapping flow on Android.

I'm talking about the "airplane mode" tile which isn't a "protected" tile: anyone can access it directly on the Android lockscreen.

A "decent" thief would directly enable airplane mode from the tiles (if available) to avoid any remote localization of the device and/or wipe.

So, do you think you would be able to do the same as you're actually doing with your tiles and create a new "airplane mode" tile would be protected by the user password?

That would be amazing !

Kind regards,

**Comment by CasperVerswijvelt** [comment]
Glad you're enjoying the app :) 

This should be fairly easy to do, but I can't give promises aout when this would be available
I'm also open to pull requests if someone wants to implement this themselves

**Comment by e-t-l** [comment]
@CasperVerswijvelt Thank you for the wonderful app. I have a slightly different use case for an Airplane Mode tile:
GrapheneOS, a security-focused android ROM, actually does protect the Airplane Mode tile (as well as Internet, Bluetooth, and Battery Saver for some godforsaken reason) just like how @CaseyBakey wants. But I find the diminished usability to be an unwelcome tradeoff for the façade of extra security (if a thief wants to disable networking, they can just turn the phone off and put it in a homemade Faraday cage). So, the fact that your app provides tiles that DON'T require unlock is actually the perfect solution. Therefore:

If you do have a chance to implement an Airplane Mode tile, please make sure users still have the option to use it WITHOUT requiring unlock.

Thank you!

**Comment by CasperVerswijvelt** [comment]
@e-t-l 
Thanks!

If implemented, an airplane mode would/should also follow the global "Requires unlock" setting

I have also created a new ticket to add more customization options and to have them on a per-tile basis (see #19 for more info/discussion)

**Comment by CasperVerswijvelt** [comment]
This feature is implemented in 3.0.0 beta 2
