### ISSUE TITLE
CAN'T ENABLE SIM CARD AGAIN!!

### ISSUE THREAD

**Issue by tkbstudios** [CasperVerswijvelt/Better-Internet-Tiles#21]
I tried the option to turn off the SIM 1 when long press the internet tile from this app and now, I can't enable my SIM again!! Please send a fix!!

**Comment by CasperVerswijvelt** [comment]
Hi, it does indeed seem that opening long pressing the mobile data icon while the sim card is disabled results in an app crash

You can still navigate to the correct page to enable the sim card again by opening opening the "Settings" app, selecting "Network and Internet", "SIM cards" and then enabling the sim again

**Comment by tkbstudios** [comment]
I tried, it shows me the SIM card is enabled but I see inside my menu that there is no sim card

**Comment by CasperVerswijvelt** [comment]
This is not something that can be caused by my app
