### ISSUE TITLE
Avoid root using WRITE_SECURE_SETTINGS ?

### ISSUE THREAD

**Issue by trytomakeyouprivate** [CasperVerswijvelt/Better-Internet-Tiles#27]
I really like this app. LineageOS seems to integrate something like that, but GrapheneOS doesnt.

I know of some apps that use this permission and dont need root in that case.

For me it sounds like this should be possible for this app, without root access. Displaying seems to work without root, just the changing is not. 

Shizuku doesnt work for me, and also disables itself after reboot, in general its a pain to use.

**Comment by trytomakeyouprivate** [comment]
RootlessJamesDSP uses this permission

**Comment by CasperVerswijvelt** [comment]
I took a quick look at this but was not able to change any settings using this method
When the WRITE_SECURE_SETTINGS permission was not granted, I got an exception saying I needed permission. After granting the permission through ADB I no longer got the exception, but my code did not seem to do anything

Tried the following things:

```
Settings.Secure.putInt(
  context.contentResolver,
  Settings.Secure.WIFI_ON,
  1
)
```

```
Settings.Secure.putInt(
  context.contentResolver,
  Settings.Global.WIFI_ON,
  1
)
```
```
Settings.Global.putInt(
  context.contentResolver,
  Settings.Global.WIFI_ON,
  1
)
```

I can't find any place in RootlessJamesDSP where this system is used, and the [manifest file](https://github.com/ThePBone/RootlessJamesDSP/blob/master/app/src/main/AndroidManifest.xml) also does not declare the `WRITE_SECURE_SETTINGS` permission. Can you show me where exactly it is used?

**Comment by firefoxlover** [comment]
hmm, thanks for looking into that! I dont know how it is used but I can ask. I think the write secure settings is to enable the internal audio stream of android? It uses this stream to manipulate the audio without needing the Equalizer API

**Comment by CasperVerswijvelt** [comment]
More info on how it is used would be very welcome

**Comment by firefoxlover** [comment]
https://github.com/ThePBone/RootlessJamesDSP/issues/172

**Comment by CasperVerswijvelt** [comment]
Seems like nothing really came out of the issue you created, so I'm going to close this issue
