### ISSUE TITLE
Hide SSID from WiFi tile

### ISSUE THREAD

**Issue by oSumAtrIX** [CasperVerswijvelt/Better-Internet-Tiles#30]
# Issue

On Google Pixel devices you have to enable or disable recording from the notification center. This exposes the network SSID in the recording. The SSID can actually be used to identify ones location thanks to city network scanning, meaning, if you share the recording online, one can lookup your address.

# Solution

Add an option to hide the network SSID. It could say "Internet" or "Connected" for example.

**Comment by CasperVerswijvelt** [comment]
Discovered that android 15 added support for detecting when screen capture is active: https://alisubhani313.medium.com/android-15s-screen-recording-detection-27349f8873cf

We could add a setting with multiple options: show, hide, hide during recording

Thoughts?

**Comment by oSumAtrIX** [comment]
Why should show and hide be an option? The only relevant toggle is the last.

**Comment by CasperVerswijvelt** [comment]
> Why should show and hide be an option? The only relevant toggle is the last.

Recording detection is only available on android 15, so earlier versions wouldn't have that option

**Comment by oSumAtrIX** [comment]
I guess you would show the show/hide toggle on A14 and the `hide during recording` on A15?

**Comment by CasperVerswijvelt** [comment]
the `hide during recording` setting is unfortunately not going to work, as the app only detects it when the app is in the foreground... I don't get the callback when screen recording and the quick settings are opened

**Comment by oSumAtrIX** [comment]
That's okay. Hiding works fine. Another suggestion for hiding the SSID would ne to simply display "Hidden" as the SSID when you are connected

**Comment by CasperVerswijvelt** [comment]
This is implemented and will be in the next release

<img width="295" alt="image" src="https://github.com/user-attachments/assets/6eec17dd-30cb-43f2-9ef2-2ad4ade53a27">
