### ISSUE TITLE
Hide Arrow Icon

### ISSUE THREAD

**Issue by atuy1219** [CasperVerswijvelt/Better-Internet-Tiles#41]
In Better Internet Tiles, tiles like Wi-Fi, mobile data, NFC, and airplane mode have arrow icons. However, if the only function of the tile is to toggle ON/OFF, then the icon is unnecessary.
![Screenshot_20240715-163203](https://github.com/user-attachments/assets/753bc7ee-336f-4d17-9da5-716c994f2311)

**Comment by CasperVerswijvelt** [comment]
Hi, I've already changed this in this commit: https://github.com/CasperVerswijvelt/Better-Internet-Tiles/commit/dc10896a4644bd1839df47e39cb7731577888d9f, but there hasn't been a new (beta) build with this change yet

**Comment by atuy1219** [comment]
When will the next beta build be released?

**Comment by CasperVerswijvelt** [comment]
Just released a new beta version :)

**Comment by atuy1219** [comment]
Thank you very much!
