### ISSUE TITLE
BIT loses superuser after reboot

### ISSUE THREAD

**Issue by burntoc** [CasperVerswijvelt/Better-Internet-Tiles#46]
I would think this might be an Apatch issue, but I'm running 6-8 modules and this only happens with BIT.  I grant superuser to it and things are great, but when I reboot superuser is gone and I have to go back into Apatch and re-enable.

Pixel 7 Pro, latest updates, latest Apatch

**Comment by bwitt** [comment]
I'm seeing this too using pixel 8a stock and magisk

**Comment by CasperVerswijvelt** [comment]
I'm using Magisk 27.0 myself and have never encountered this issue.

For the Magisk users (@bwitt @moritzruth): does it give the SU request popup by itself when opening the BIT app or do you need to manually grant it in Magisk manager?

I've never used Apatch before so I can't really comment on that unfortunately

**Comment by burntoc** [comment]
I can say that while it was absolutely consistent and I could not get it to work even with uninstall/reinstalls,  I had to do a clean install on that P7P and it worked fine again.  I have a P8P now and it is working fine here, so whatever causes it seems to be quite uncommon.  If not for @bwitt's comment I guess I'd close this, but it rare - not unique.

**Comment by bwitt** [comment]
it's working for me now!  after rebooting  I see the dialog box flash about granting superuser and the tiles work great

**Comment by burntoc** [comment]
Based on the latest info I'll close it!

**Comment by burntoc** [comment]
It's become an issue again since the Android 15 update. This and FX explorer are the only 2 apps of about a dozen I use which fail to recognize they've been granted root (latest Apatch). BIT is the only one that keeps disappearing from the granted list altogether after reboot. FX at least shows up

**Comment by Albirew** [comment]
Same kind of issue: BIT seems to forget it already has root and asks for it again after reboot and/or some time
how i found it:
wifi tile doesn't update -> tapping on it -> BIT asks for root or shizuku -> tap on OK -> it opens BIT main window -> close it since it remembers it has root and tile now works until it forgets again (random time? a week?)

Pixel 7 with GrapheneOS and Magisk.
Behavior started after i updated to Android 15 and Magisk 28.1 (was previously forced to stay on Android 13 and Magisk 27)

**Comment by AutomaticFailure** [comment]
Ongoing annoyance for a long while now. Once I get the popup and go through that, it tends to work 'normally' for a few, then right back at it.
Rooted, Magisk, Pixel 7a, Android 15, all permissions required. Toggle for mobile data on/off.

**Comment by TheRetenor** [comment]
Same issue on Android 13, Sony XQ-BQ52, Magisk 29.0, Sui 13.5.1, LSPosed 1.10.2. Root access granted indefinitely via shell method root.
This was not an issue in an older version though, at least for me. My previously installed version was from ~March 2023.
Besides the tiles not being active and the popup occurring, it also from time to time marks my SIM as unavailable, while it is normally selected in the Network settings.
Opening the app once fixes the issue. Battery optimization set to unrestricted.

**Comment by AngryManMLS** [comment]
Same issue is still occurring on Android 16 on my Pixel 9 Pro XL (Komodo) regardless of which QPR or beta or whatever I am on. Using Magisk 30.6 and ReLSPosed  v1.0.1 (7210) presently on Android 16 QPR2 December. Thankfully it looks like the developer is tagging stuff to work on so hopefully this bug will be squished in the near future. Thanks for this great mod.
